### ISSUE TITLE
Reverse proxy with traefik not working

### ISSUE THREAD

**Issue by cybermcm** [mikesplain/openvas-docker#235]
I'm trying to get the container working behind a traefik reverse proxy. I managed to get it working with 443 -> 80 but this results in a warning message during logon. So my goal is to get it done by traefik port 443 -> openvas port 443.

compose:
```
 openvas:
  container_name: openvas
  environment:
   - OV_PASSWORD=xxx
   - PUBLIC_HOSTNAME=vas.xxx.net
  image: mikesplain/openvas:latest
  labels:
   - traefik.enable=true
   - traefik.port=443
   - traefik.frontend.rule=Host:vas.xxx.net
   - traefik.frontend.auth.forward.tls.insecureSkipVerify=true
   - traefik.protocol=https
  networks:
   - web
  restart: always
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /opt/openvas:/var/lib/openvas/mgr
```
currently the following error is reported in traefik:
```
level=debug msg="Error calling . Cause: Get : unsupported protocol scheme \"\""
```
Any ideas how to get this done (other containers working well behind reverse proxy)?
